Azure/cyclecloud-slurm

- README.md
> Slurm documentation for 7.8.0

- specs/default/chef/site-cookbooks/slurm/files/default/cyclecloud_slurm.py
- specs/default/chef/site-cookbooks/slurm/recipes/scheduler.rb
install the terminate_nodes.sh helper on scheduler and add the command parser
> install the terminate_nodes.sh helper on scheduler 

- specs/default/cluster-init/tests/test_uid.py
Cannot strip an int object returned by jetpack.config.get()
> [TRIVIAL] Fix test_uid

- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/recipes/accounting.rb
- specs/default/chef/site-cookbooks/slurm/recipes/default.rb
- specs/default/chef/site-cookbooks/slurm/recipes/execute.rb
> Add RHEL support

- docker-rpmbuild.sh
- project.ini
- specs/default/chef/roles/slurm_login_role.rb
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/files/default/cyclecloud_slurm.py
- specs/default/chef/site-cookbooks/slurm/libraries/helpers.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/chef/site-cookbooks/slurm/recipes/execute.rb
- specs/default/chef/site-cookbooks/slurm/recipes/login.rb
- specs/default/chef/site-cookbooks/slurm/recipes/scheduler.rb
- specs/default/chef/site-cookbooks/slurm/templates/default/slurm.conf.erb
- specs/default/cluster-init/files/00-build-slurm.sh
- templates/slurm-custom.txt
- templates/slurm.txt
Fix deallocation hostname issues.
Fix interactive bug where ip-* hostname nodes would join before their IP address was set. (Work around to Slurm issue).
> 2.6.1 improvements

- templates/slurm-cs.txt
- templates/slurm.txt
Adds this image for scheduler, hpc, htc and dynamic partitions.
> Add sles12 and sles15 to image names

- templates/slurm-cs.txt
- templates/slurm.txt
Changes default scheduler VM type to allow hypervisor to boot.
> Change default scheduler VM type.

- slurm/install/installlib.py
Fix the bug where /etc/waagent.conf was not getting overwritten.
> BugFix: Waagent.conf was not getting overwritten.

- slurm/src/slurmcc/allocation.py
User can add other custom feature flags for convenience i.e. `Feature=dyn,Standard_F4,test`. Note: If multiple VM sizes are enabled on the partition, a full VM size name will still be required to start the correct VM.
> Allow custom features on dynamic partitions

- slurm/install/package.py
- slurm/install/suse.sh
- templates/slurm.txt
Adds Suse support only for slurm 22.05. Removes cycle.image.sles12.
> Add SuSe support for Slurm 22_05

- README.md
- project.ini
- slurm/install/setup.py
- slurm/install/slurm_supported_version.py
- slurm/setup.py
- slurm/src/slurmcc/cli.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/cluster-init/files/install-non-scheduler.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- templates/slurm-cs.txt
- templates/slurm.txt
Update slurm versions to 22.05.9 and 23.02.4
And update packages for binary release.
> Update version number to 3.0.3

- slurm/src/slurmcc/partition.py
Allow standard_* features to be set so that we do not conflict with customer environments
> Allow node features that match standard_*, as to not conflict with customer environments

- slurm/src/slurmcc/allocation.py
> Exclude fully deallocated nodes as existing nodes in resume

- templates/slurm.txt
> Remove ComputerName from scheduler-ha nodearray

- package.py
> Use latest version of scalelib - 1.0.1

- README.md
- project.ini
- slurm/install/setup.py
- slurm/setup.py
- slurm/src/slurmcc/cli.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/cluster-init/files/install-non-scheduler.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- templates/slurm-cs.txt
- templates/slurm.txt
> Bump versions to 3.0.4

- package.py
- project.ini
- slurm/install/slurm_supported_version.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
Update binary release
Update cyclecloud api version
Add slurm-slurmrestd to packages downloaded from bins release.
> Update bins release to 2023-09-14

- slurm/install/ubuntu.sh
> Install hwlocs for ubuntu

- project.ini
- slurm/install/setup.py
- slurm/setup.py
- slurm/src/slurmcc/cli.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/cluster-init/files/install-non-scheduler.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- templates/slurm-cs.txt
- templates/slurm.txt
> Update azslurm to 3.0.5

- templates/slurm.txt
Enable node healthchecks in slurm templates.
> Enable node healthchecks

- slurm/src/slurmcc/cli.py
- specs/scheduler/cluster-init/tests/test_slurm.py
If azure.conf or gres.conf already exist, maintain ownership/permissions when replacing them during azslurm scale
Fixes: #193
> Maintain azure.conf and gres.conf permissions between azslurm scale calls

- slurm/src/slurmcc/cli.py
- slurm/src/slurmcc/util.py
Detect that autoscale is not enabled and then append --future to scontrol show nodes. Note that we needed to move is_autoscale_enabled to util.py to do this.
Fixes: #202
> Fix: Append —future to local node_list command

- project.ini
- slurm/install/rhel.sh
- slurm/install/slurm_supported_version.py
- slurm/install/ubuntu.sh
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- templates/slurm.txt
Adds new slurm versions
Add libmysqlclient for ubuntu
> Bump slurm packages and add new slurm version

- install.sh
Fail if no jetpack is found unless the user explicitly sets --no-jetpack
> Add --no-jetpack option to install.sh for non-jetpack installations

- slurm/install/install.py
- slurm/install/templates/slurmdbd.conf.template
- templates/slurm.txt
That is a misconfiguration of slurm. Also adds a warning for the users to inform them that they are responsible for purging/archiving the database once cluster is deleted.
> Add storageloc parameter to prevent multiple slurmdbd's from talking to the database

- README.md
Add documentation noting the behaviour change for dynamic nodes.
Also fix the documentation.
> Add documentation for dynamic nodes behaviour change.

- README.md
- project.ini
- slurm/install/setup.py
- slurm/install/slurm_supported_version.py
- slurm/setup.py
- slurm/src/slurmcc/cli.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/cluster-init/files/install-non-scheduler.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- templates/slurm-beegfs.txt
- templates/slurm-cs.txt
- templates/slurm-custom.txt
- templates/slurm.txt
- Project version updated to 3.0.9
- slurm versions updated to 23.11.9-1, 23.02.8-1
- Centos7 images removed from templates as centos7 is of support.
> Update project to 3.0.9 and update slurm versions.

- slurm/install/install.py
DB name needs to be escaped differently from clusternames because db names cannot have "-" as mysql rejects it.
https://github.com/Azure/cyclecloud-slurm/issues/279
> Fix database naming for slurm clusters

- slurm/install/rhel.sh
https://github.com/Azure/cyclecloud-slurm/issues/285
> Install slurm-contribs package

- README.md
- project.ini
- slurm/install/setup.py
- slurm/install/slurm_supported_version.py
- slurm/setup.py
- slurm/src/slurmcc/cli.py
- specs/default/chef/site-cookbooks/slurm/attributes/default.rb
- specs/default/chef/site-cookbooks/slurm/metadata.rb
- specs/default/cluster-init/files/install-non-scheduler.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- templates/slurm-cs.txt
- templates/slurm.txt
Update slurm versions and add rhel 9 builds.
> Update to 3.0.10

- .gitignore
- docker-package.sh
Also includes fixes for better readability.
Script will exit if any uncommitted changes are present. Script will also delete pre-existing blobs.
> Fix docker_package.sh to exit if working directory is dirty.

- slurm/src/slurmcc/util.py
adding partition option to srun command to run commands on a specific partition if requested.
> adding partition option to srun command

- project.ini
- templates/slurm.txt
Update project.ini to support slurm versions 24.05.6-1 and 24.11.3-1
> bump supported slurm version to 24.05.6-1 and 24.11.3-1

- slurm/install/ubuntu.sh
modify ubuntu.sh to include ubuntu24 support for both amd64 and arm64 architectures
> add ubuntu24 support

- README.md
Update README.md to incorporate recent changes.
Add a section for the topology cli 
Add a note about disabling PMC being removed in the new version
Add a Table of Contents
> Update README.md to incorporate recent changes

- azure-slurm-install/install.py
Additionally the plugstask.conf.d directory is local to each node.
> Add plugstack.conf files for adding spank plugins

- azure-slurm-install/ubuntu.sh
Any version string that starts with 24 will work in this case, Current GB200 image appears to be 24.10
> Detect ubuntu24 version

- README.md
- azure-slurm-install/imex_epilog.sh
- azure-slurm-install/imex_prolog.sh
- azure-slurm-install/install.py
- azure-slurm-install/package.py
- templates/slurm.txt
add imex_prolog.sh and imex_epilog.sh into azure-slurm-install and copy them to /sched/<cluster-name>/prolog.d and /sched/<cluster-name>/epilog.d respectively.
> Integrate IMEX Prolog and Epilog scripts into azure-slurm-install

- azure-slurm/slurmcc/util.py
add optional gpus flag to srun cli to run nvidia-smi commands
> add gpus flag to srun cli

- templates/slurm.txt
- And fix slurm cluster init name
> Add healthagent project

- azure-slurm-install/imex_epilog.sh
- azure-slurm-install/imex_prolog.sh
- azure-slurm-install/templates/slurm.conf.template
Run prolog script on allocation rather than first task launch.
> Fix IMEX prolog integration

- README.md
update the readme to include new changes including block topology plugin for azslurm topology cli
> update readme for topology cli

- azure-slurm-install/package.sh
- azure-slurm/install.sh
- azure-slurm/package.py
- azure-slurm/package.sh
- docker-package.sh
- specs/scheduler/cluster-init/scripts/00-install.sh
- util/Dockerfile
Make changes for using python3.11 in preparation for azslurmd.
> Use python3.11+

- templates/slurm.txt
Proposal to change default OS to ubuntu22 in 4.x
> Change default OS to ubuntu22

- README.md
- azure-slurm-install/capture_logs.sh
- azure-slurm-install/install.py
- azure-slurm-install/package.py
Add a script to capture relevant logs and configuration data from a node. (scheduler or execute)
> Add a capture script

- azure-slurm-install/imex_prolog.sh
Default config file already contains the default port. Don't change it.
> Make imex port static.

- templates/slurm.txt
> Ubuntu 22 is now the default, and removed Ubuntu 20 as an option
