Azure/cyclecloud-slurm

specs/default/chef/site-cookbooks/slurm/recipes/scheduler.rb

xargs has a maximum length and will cause issues if the /etc/hosts file is very long (for example a /18 subnet). Use `paste` instead which doesn't seem to have this issue

Don't use xargs to generate the node name list 

---

.gitignore
README.md
docker-rpmbuild.sh
project.ini
specs/default/chef/site-cookbooks/slurm/recipes/default.rb
specs/default/chef/site-cookbooks/slurm/recipes/execute.rb
specs/default/chef/site-cookbooks/slurm/recipes/scheduler.rb
specs/default/cluster-init/files/00-build-slurm.sh
templates/slurm.txt

* Remove file modes from symlinks, to knock out the `File.lchmod` calls
which are failing.
* Remove deprecated `add_target` instructions.
* Add docker-rpmbuild.sh helper script, and documentation
* Add missing build time dependencies to build helper script
* Bump version to 1.0.2

Update Slurm project

---

project.ini
specs/default/chef/site-cookbooks/slurm/attributes/default.rb
specs/default/chef/site-cookbooks/slurm/recipes/default.rb
specs/default/cluster-init/tests/test_uid.py
templates/slurm.txt

Set UID/GID for slurm and munge users explicitly to remove dependency on user creation order.
This is particularly important with the new CycleCloud user management features.

Set UID/GID for slurm and munge users explicitly 

---

project.ini
specs/default/chef/site-cookbooks/slurm/recipes/default.rb

Install EPEL and munge as a dependency on CentOS, so that cyclecloud-slurm
continues to work on CycleCloud 8.

Install EPEL as a dependency

---

specs/default/chef/site-cookbooks/slurm/files/default/cyclecloud_slurm.py

formula updated to divide memory by cpus instead of pcpu to accurately calculate Hyperthreaded VMs

update def_mem_per_cpu calculation

---

templates/slurm.txt

use vcpus for calculating cyclecloud.conf resources

set slurm.use_pcpu = false for htc

---

templates/slurm.txt

disable the export if an external Sched is used as required for HA config

add exports.builtinsched.disabled = ${NFSSchedDisable} for HA

---

templates/slurm-beegfs.txt
templates/slurm-custom.txt
templates/slurm.txt

Change D12_v2 to D16_v4, better default price / performance value and supports hyperv gen2.
gen 2 support matrix: https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2

Update default instance type

---

dev-requirements.txt
install.sh
package.py
sbin/prolog.sh
slurm/conf/logging.conf
slurm/install/install.py
slurm/install/templates/slurm.conf.template
slurm/setup.py
slurm/src/slurmcc/cli.py
slurm/src/slurmcc/cost.py
slurm/src/slurmcc/util.py

Adds cost reporting to slurm accounting and creates a new `azslurm cost` CLI to append costs to slurm accounting data.
Also adds a prolog slurmctld script that records vm size related information such as sku, region, priority, cpu/gpu counts etc and stores them in admincomment field in slurm, so that cost reporting can fetch relevant cost data.

Slurm accounting with cost reporting

---

specs/default/chef/site-cookbooks/slurm/recipes/scheduler.rb
specs/default/cluster-init/files/install-non-scheduler.sh
specs/execute/cluster-init/scripts/00-install-execute.sh
specs/login/cluster-init/scripts/00-install-login.sh

Run slurm installation on login nodes, so slurm binaries are accessible from login nodes. Allows users to run `squeue`, `srun` etc from the logins.

Fix login nodes and Remove unused chef recipes

---

slurm/install/install.py

Slurmd on dynamic nodes needs to start with "-b" if its not already been specified in the template.

Add "-b" to  slurmd config for dynamic nodes

---

build.sh
slurm/install/install.py
slurm/install/package.py
slurm/install/templates/slurmdbd.conf.template
templates/slurm.txt

Azure Maria DB now requires combined SSL client certificates from 2 authorities. . This PR fixes the client certificates used by Azure Maria DB, and also adds a new certificate_url option for user to specify the certificate. If a user has specified certificate then it is used.
The issue is described here: https://learn.microsoft.com/en-us/azure/mariadb/concepts-certificate-rotation?WT.mc_id=Portal-SqlAzureExtension

Fix SSL certificates used for accounting

---

templates/slurm.txt

Certificate url needs to be a parameter defined in the templates.

Add Certificate_url to slurm templates.

---

slurm/src/slurmcc/partition.py
slurm/src/slurmcc/util.py

Prevents querying of node names while scontrol is down
Regression from PR 138

Prevent querying for dynamic node names while slurmctld is down.

---

sbin/prolog.sh

Slurm binaries can be present under /bin or /usr/bin.

Prolog slurmctld script needs to use correct binaries.

---

templates/slurm.txt

For dynamic partitions having the default of allowing multiple VM sizes as default makes them more useful.

For dynamic partition make config.MultiSelect true by default.

---

specs/default/chef/site-cookbooks/slurm/attributes/default.rb

A workaround for something some users are experiencing - cuser.base_home_dir is set to /home instead of /shared/home in some environments.
Fixes #153

Set cuser.base_home_dir default to /shared/home as a workaround

---

slurm/install/slurm_supported_version.py
util/build-slurm.sh
util/docker-rpmbuild.sh

Updates build to use pmix 4.2.6 due to a CVE.
Updates build options to build slurmrestd.
Updates slurm version to 23.02.5
For builds, use mcr container images.

Add slurm 23.02.5 and use pmix 4.2.6

---

install.sh
slurm/install/install.py
slurm/src/slurmcc/cli.py

This makes persistent /sched on an external NFS use case work correctly.

Get config files written under a cluster-name dir inside /sched.

---

templates/slurm.txt

Suse now has 23.02 RPMS available, so remove warnings.

Update templates to point to correct version of slurm.

---

templates/slurm.txt

1) by default, put Scheduler VM into Availability Zone 1 and Scheduler-HA VM into Availability Zone 2 (but only when HA is enabled)
2) parameterize the zones for the two schedulers

Add zone parameters to deploy main/backup schedulers when HA is enabled.

---

.gitignore
project.ini
slurm/install/package.py
slurm/install/rhel.sh
slurm/install/slurm_supported_version.py
slurm/install/ubuntu.sh
specs/default/chef/site-cookbooks/slurm/attributes/default.rb
templates/slurm.txt
util/Dockerfile

- Use updated artifacts.
- Fix our packaging scripts to make use of the updated artifacts and group all artifacts by distros. 
- Adds ubuntu22 to supported images

Update slurm versions and use new artifacts created via ADO.

---

install.sh

Use lower case ClusterId tag name, and a sane default, for accounting

---

README.md
install.sh
slurm/install/install.py
slurm/install/templates/slurm.conf.template
slurm/install/templates/slurmdbd.conf.template
templates/slurm.txt

In order to work with Azure MariaDB instances, we had to explicitly add a certificate authority in the StorageParameters. This is no longer needed. This PR still leaves this as an option, by converting Accounting Certificate URL to an editable dropdown with AzureCA.pem as an option.

No longer assume AzureCA.pem is required for job accounting

---

slurm/install/ubuntu.sh

The single brackets just meant that it is writing a file called "19" to the current working directory.  It also always evaluates to true unless UBUNTU_VERSION is empty.

Fixing incorrect if statements

---

slurm/src/slurmcc/cli.py

Fixes: #197
Leaves a commented out field for SuspendExcNodes instead of an invalid, blank SuspendExcNodes=

Fix keep_alive after all nodes are removed

---

slurm/install/install.py
slurm/install/package.py
slurm/install/rhel.sh
slurm/install/slurmel7.repo
slurm/install/slurmel8.repo
slurm/install/ubuntu.sh
templates/slurm.txt

This commit adds packages.microsoft.com repositories as source for slurm rpms and debs. Packages are fetched during installation. There is also an option added to disable fetching packages from PMC and complete the installation in the traditional way.

Add PMC repositories as sources for slurm binaries.

---

README.md
slurm/install/install.py
slurm/install/installlib.py

Ubuntu 22 or greater and DNS hostname resolution
Due to an issue with the underlying DNS registration scheme that is used across Azure, our Slurm scripts use a mitigation that involves restarting `systemd-networkd` when changing the hostname of VMs deployed in a VMSS. This mitigation can be disabled by adding the following to your `Configuration` section.
[[[configuration]]]
slurm.ubuntu22_waagent_fix = false
In future releases, this mitigation will be disabled by default when the issue is resolved in `waagent`.
Fixes: #203

Ubuntu22: Mitigation for waagent's failure register DNS

---

README.md
install.sh
slurm/src/slurmcc/partition.py

Per README.md additions: 
For some regions and VM sizes, some subscriptions may report an incorrect number of GPUs. This value is controlled in `/opt/azure/slurm/autoscale.json`
The default definition looks like the following: 
```json
"default_resources": [
{
"select": {},
"name": "slurm_gpus",
"value": "node.gpu_count"
}
],
```
Note that here it is saying "For all VM sizes in all nodearrays, create a resource called `slurm_gpus` with the value of the `gpu_count` CycleCloud is reporting".
A common solution is to add a specific override for that VM size. In this case, `8` GPUs. Note the ordering here is critical - the blank `select` statement will set the default for all possible VM sizes and all other definitions will be ignored. For more information on how scalelib `default_resources` …

Allow local override of GPUs

---

templates/slurm.txt

Refactor the network attached storage configuration blade to allow mounting /sched AND an additional /data FS 
Add support for AMLFS as well as NFS

Refactor the network attached storage configuration

---

package.py

Use the latest version of scalelib, including the latest embedded VM Size information for certain locked down environments.

Use latest version of scalelib - 1.0.2

---

README.md
slurm/src/slurmcc/cli.py
slurm/src/slurmcc/partition.py
slurm/src/slurmcc/util.py
slurm/test/slurmcc_test/testutil.py

Fixes: #30
Related new documentation:
Slurm requires that you define the amount of free memory, after OS/Applications are considered, when reporting memory as a resource. If the reported memory is too low, then Slurm will reject this node. To overcome this, by default we dampen the memory by 5% or 1g, whichever is larger.
To change this dampening, there are two options.
1) You can define `slurm.dampen_memory=X` where X is an integer percentage (5 == 5%)
2) Crate a default_resource definition in the /opt/azurehpc/slurm/autoscale.json file. 
```json
"default_resources": [
{
"select": {},
"name": "slurm_memory",
"value": "node.memory"
}
],
```
Default resources are a powerful tool that the underlying library ScaleLib provides. [see the ScaleLib …

slurm.dampen_memory was ignored

---

templates/slurm-beegfs.txt
templates/slurm-custom.txt

Ganglia is no longer used by CycleCloud

Remove ganglia input endpoints from template

---

sbin/prolog.sh

For certain cron jobs in slurm, running scontrol update command is blocked by slurm. This allows the user to cron jobs via scrontab. The downside is that the admin comment field won't be populated for these jobs.

Make scontrol update command always return true.

---

templates/slurm.txt

Incorrect mount was referenced in the documentation, which could cause confusion. Update fixes the typo.

fix typo in template widget

---

slurm/src/slurmcc/util.py

During installation, since we start services later, scontrol commands appear to be hanging, and especially in HA mode where it attempts to talk to backup slurm controller.

In slurm > 23.11 scontrol commands hang if slurmctld is not running.

---

slurm/install/rhel.sh
slurm/install/ubuntu.sh

Jq is used by prolog scripts and in some cases is not present in the image.
mysql client libraries are replaced by mariadb. 
Note: With the exception of jq, most of these packages shouldnt be required once we fully move to PMC.

Add some runtime dependencies needed for our scripts.

---

slurm/install/install.py

Also adds correct hostname for slurmdbd node, that allows login nodes to run sacct, sacctmgr

Enable Slurmdbd HA

---

slurm/src/slurmcc/cost.py

If somehow admincomment gets set to [], ignore and process other jobs.

BugFix: Cost module breaking on list index out of range.

---

README.md
package.py
sbin/return_to_idle.sh
sbin/return_to_idle_legacy.sh
slurm/src/slurmcc/cli.py
slurm/src/slurmcc/partition.py
slurm/src/slurmcc/util.py
slurm/test/slurmcc_test/allocation_test.py
slurm/test/slurmcc_test/cli_test.py
slurm/test/slurmcc_test/testutil.py

Fixes issues with manually suspending nodes that do not use nodename==hostname.
Also fixes KeepAlive issues where the nodes would resume/resume_failed in a loop forever.
Adds azslurm return_to_idle command to help with this, rather than the pure shell implementation.

Fix manual suspend and avoid KeepAlive=true resume/resume_fail loop via new azslurm return_to_idle command

---

slurm/install/rhel.sh

This PR is intended to fix issue #126 .
The powertools repository is not compatible nor required for RHEL only for CentOS

Fix powertools installation for RHEL

---

slurm/src/slurmcc/cli.py
slurm/src/slurmcc/partition.py

When users hit 0 capacity issues, currently the only way for them to detect that is by checking the logs. This PR will leave the definition of the partition in azure.conf, but will comment it out with a comment that this particular partition/nodearray/vm_size has 0 capacity.
For example, I have 0 capacity for the ND40 here, this is what azslurm partitions writes out (and azslurm scale would put into /etc/slurm/azure.conf)
\# The following partition has no capacity! htc - htc - Standard_ND40rs_v2
\# PartitionName=htc Nodes= Default=NO DefMemPerCPU=16343 MaxTime=INFINITE State=UP
\# Nodename=[] Feature=cloud STATE=CLOUD CPUs=40 ThreadsPerCore=1 RealMemory=653721 Gres=gpu:8

leave a comment about 0 capacity unused partitions

---

slurm/src/slurmcc/partition.py

If some dynamic nodes get added on the command line without the feature set associated with dynamic partition, then slurm still registers those nodes but does not associate them with a partition. In "scontrol show nodes" the partition field then appears blank resulting in a key error. This fixes that.

Bug Fix: Fix azslurm partitions command.

---

slurm/src/slurmcc/util.py
slurm/test/slurmcc_test/util_test.py

Removes str vs int comparison bug by always converting the key to an integer. In this case, simply convert the string as bytes into an integer.

Always convert the sort key to an integer when sorting node names

---

templates/slurm.txt

Fixed some typos and spliced commas. Happy to undo the changes of "filesystem" to "file-system" made here for consistency.

Fixes of some grammar and typos

---

templates/slurm.txt

These changes allow users to switch from external NFS to builtin sched without issue.

Set sched to be persistent

---

slurm/install/install.py
slurm/src/slurmcc/cli.py
slurm/src/slurmcc/partition.py
templates/slurm.txt

Dynamic nodes that are precreated need slurmd to start with "gres:gpu:<gpu_count" option, otherwise they get invalid registration in `sinfo` and are unschedulable.

Fix slurmd startup for dynamic GPU nodes

---

slurm/install/install.py
slurm/install/templates/munge.override

Also avoid creating another munge service which
we do not use.

Set munge service to restart always

---

slurm/install/templates/slurm.conf.template
slurm/src/slurmcc/util.py

commands that need to be run across a range of compute nodes can be submitted through srun. The interface exposed is similar to subprocess but based on srun.
This does use the job scheduler.

Add an srun interface for submitting parallel commands.

---

slurm/src/slurmcc/topology.py
slurm/src/slurmcc/util.py

edit srun interface to include stderr of srun process and srun command. Fix logging in topology.py to to log every line of stderr output from SrunExitCodeException.

Fix srun logging to output all stderr

---

azure-slurm-install/ubuntu.sh

fix spacing in line 37 of ubuntu.sh to be [ "$arch" not ["$arch"

fix spacing in conditional

---

templates/slurm-beegfs.txt
templates/slurm-cs.txt
templates/slurm-custom.txt
templates/slurm.txt

Default chef attributes were used in 3.x to assign a value to slurm.role, but in our chefless implementation this is not possible at the moment.

Add slurm.role to 4.x templates

---

templates/slurm.txt

with the change to using Node count vs cores, there is no way to not use a paritition type.  Changing the `Config.MinValue = 0` for HTC, HPC and GPU will enable a value of 0 nodes in the UI, which will not build that partition.  It can also be added or removed later with azslurm scale.

change min node value to 0

---

slurm/src/slurmcc/util.py
slurm/test/slurmcc_test/testutil.py
slurm/test/slurmcc_test/util_test.py

3.x implementation of max arg fix - when invoking scontrol with variable length args (i.e. lists of nodes) cap them at 500. There is an environment variable that can be changed - AZSLURM_MAX_NODES_IN_LIST - if even 500 is too many.

Large cluster bugfix: max arg limit reached

---

templates/slurm.txt

"Deallocate" doesn't work properly with Slurm clusters, so removing the option from the default template.

Remove shutdown policy option

---

azure-slurm-install/install.py
azure-slurm-install/templates/slurm.conf.template
templates/slurm.txt

Enable healthagent based healthcheck configuration for slurm clusters.
If in the template `slurm.enable_healthchecks` is set to `false`, then `HealthCheckInterval` parameter is set to 0 which disables Healthchecking in slurm. (healthagent always runs regardless).
HealthCheckInterval is set 120secs.
This also enables health epilog.

Add slurm health check configuration.

---

specs/scheduler/cluster-init/scripts/00-install.sh

00-install.sh fails due to a missing space between a bracket under some shells.

fix: space after ] in 00-install.sh

---

azure-slurm/slurmcc/topology.py
azure-slurm/test/slurmcc_test/topology_test.py

add new function output_block_nodelist that  takes in a topology file or string and outputs a sorted list of blocks by the size of their node list in either json or tabular format. 
With a topology like this 
```
BlockName=block_5e797fc6-0f46-421a-8724-0e102c0f723c_1234 Nodes=hpcbench-hpc-9,hpcbench-hpc-13,hpcbench-hpc-17,hpcbench-hpc-21,hpcbench-hpc-25,hpcbench-hpc-29,hpcbench-hpc-33,hpcbench-hpc-37,hpcbench-hpc-41,hpcbench-hpc-45,hpcbench-hpc-49,hpcbench-hpc-53,hpcbench-hpc-57,hpcbench-hpc-61,hpcbench-hpc-65,hpcbench-hpc-69
BlockName=block_5e797fc6-0f46-421a-8724-0e102c0f721e_23456 Nodes=hpcbench-hpc-22,hpcbench-hpc-26,hpcbench-hpc-30,hpcbench-hpc-34,hpcbench-hpc-38,hpcbench-hpc-42,hpcbench-hpc-46,hpcbench-hpc-50,hpcbench-hpc-54,hpcbench-hpc-58,hpcbench-hpc-62,hpcbench-hpc-66,hpcbench-hp …
```

Output sorted list of blocks for block topology cli

---

scale_m1/mock.py
scale_m1/scale_to_n_nodes.py

Add rotating file handler (/opt/azurehpc/slurm/logs/scale_m1.log) and console handler for logging 
Add a --filter-states argument for scale_m1 create_reservation commands to override default states to exclude when creating a reservation (default is "reserved,maint,allocated,mixed")
Fix assertion bug

Add --filter-states argument for scale_m1 create reservation and file and console handler for logging

---

azure-slurm-install/package.py
azure-slurm-install/rhel.sh
util/Dockerfile

creates _download function in package.py to download files during buildtime.
downloads epel-release-latest-8.noarch.rpm and epel-release-latest-9.noarch.rpm to artifacts dir during build and adds it to tar file
rhel.sh installs epel-release from artifacts dir for both rhel and almalinux if not already installed

download epel-release at build time
